version: '3'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80" # Map port 3000 on your host to port 80 in the container
    depends_on:
      - server # Ensure the server is started before the client

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:5000" # Map port 8080 on your host to port 3000 in the container
