version: '3'

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        - ARCH=amd64
    image: idenmorisha/safe-courier-backend:latest
    depends_on:
      - mongo

  # MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Uncomment the following section if you want to include the 'client' service
  # client:
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #     args:
  #       - ARCH=amd64
  #   image: idenmorisha/safe-courier-frontend:latest

volumes:
  mongo_data:
