# use version 3
version: "3"
services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=s3cr3tpwd
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:3.2
volumes:
  mongo-db:
